# Example override configuration for ad-hoc experiments.

paths:
  data_dir: ../../../datasets/training/adjusted/pilot_batch_Dockground_MAF2/1AVW
  label_file: null
  work_dir: ./config_run
  output_file: ./config_run/preds.csv
  checkpoint: null

batch_size: 256
num_workers: 0

builder:
  jobs: 2

options:
  reuse_existing_graphs: true
