paths:
  train_labels: ./data.train.csv
  val_labels: ./data.validate.csv
  save_dir: ./training_runs
  graph: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/graph_builder2/output/MoL_edge_10A/graph_data
model:
  pooling_type: mean
  attention_head: 8
dataloader:
  batch_size: 12
  num_workers: 0
  seed: 888
selection:
  primary_metric: val_loss
trainer:
  accelerator: cpu
  devices: 1
  precision: 32
  num_epochs: 360
  accumulate_grad_batches: 48
  use_val_spearman_as_secondary: true
  spearman_secondary_weight: 1.0
optimizer:
  learning_rate: 2e-3
scheduler:
  factor: 0.3
  patience: 25
  type: reduce_on_plateau
early_stopping:
  patience: 50
mlflow:
  enabled: true
  tracking_uri: ./qtdaqa/new_dynamic_features/model_training/ml_runs
  experiment: dynamic_topoqa
  log_artifacts: true
coverage:
  fail_on_missing: false
  minimum_percent: 0
