paths.graph: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/graph_builder2/output/lap_lean_10A_ARM/graph_data
trainer.num_epochs: 420
early_stopping.patience: 80
scheduler.patience: 20
scheduler.factor: 0.2
optimizer.learning_rate: 5e-4
dataloader.seed: 555
