paths:
  train_labels: ./smoke_test.train.csv
  val_labels: ./smoke_test.validate.csv
  save_dir: ./training_runs
model:
  pooling_type: mean
  attention_head: 4
dataloader:
  batch_size: 4
  num_workers: 0
  seed: 222
selection:
  primary_metric: val_loss
trainer:
  accelerator: cpu
  devices: 1
  precision: 32
  num_epochs: 5
  accumulate_grad_batches: 1
  use_val_spearman_as_secondary: false
optimizer:
  learning_rate: 0.005
scheduler:
  factor: 0.2
  patience: 2
  type: reduce_on_plateau
early_stopping:
  patience: 3
mlflow:
  enabled: true
  tracking_uri: ./qtdaqa/new_dynamic_features/model_training/ml_runs
  experiment: dynamic_topoqa
  log_artifacts: true
coverage:
  fail_on_missing: false
  minimum_percent: 0
